### ISSUE TITLE
Use const-generics

### ISSUE THREAD

**Issue by gendx** [gendx/lzma-rs#19]
For now, the `DecoderState` and `BitTree` structs use memory allocations (in `Vec`) to store their state, despite having sizes known at compile time. This is in the most part to avoid code duplication.

Once [const generics](https://github.com/rust-lang/rust/issues/44580) are stable enough, they should be used instead to remove the need for dynamic allocation, and make the whole state struct more compact and contiguous (therefore potentially more cache-friendly).

This should hopefully improve performance a bit.

**Comment by npmccallum** [comment]
Const generics are now stable in 1.51.

**Comment by gendx** [comment]
I had a brief look, the [`min_const_generics` feature](https://github.com/rust-lang/rust/issues/74878) was indeed stabilized in 1.51, but we still need the more complex [`const_evaluatable_checked` feature](https://blog.rust-lang.org/2021/02/26/const-generics-mvp-beta.html#const-generics-with-complex-expressions) due to the `1 << num_bits` expression [here](https://github.com/gendx/lzma-rs/blob/v0.2.0/src/decode/rangecoder.rs#L164).

In the meantime, it might be worth experimenting with it on nightly to see if benchmarks would improve with const generics.

**Comment by chyyran** [comment]
I've been doing some experiments in https://github.com/chyyran/lzma-rs/commits/feature-perf-experiments and found that const generics in `BitTree` and `RangeCoder` doesn't actually contribute that much performance benefit, *except for large dictionaries*.

https://github.com/chyyran/lzma-rs/commit/fba32253c8fdca54b10379caa092d2d6a17d6984
```
running 8 tests
test compress_65536                  ... bench:   1,359,753 ns/iter (+/- 94,903)
test compress_empty                  ... bench:         701 ns/iter (+/- 45)
test compress_hello                  ... bench:       1,011 ns/iter (+/- 208)
test decompress_after_compress_65536 ... bench:   2,445,491 ns/iter (+/- 93,723)
test decompress_after_compress_empty ... bench:       1,841 ns/iter (+/- 93)
test decompress_after_compress_hello ... bench:       2,345 ns/iter (+/- 102)
test decompress_big_file             ... bench:   3,864,228 ns/iter (+/- 257,509)
test decompress_huge_dict            ... bench:       2,354 ns/iter (+/- 182)

test result: ok. 0 passed; 0 failed; 0 ignored; 8 measured; 0 filtered out; finished in 18.29s
```

With (const generic'd) https://github.com/chyyran/lzma-rs/commit/b46d474679df58cfe3790b522a98e3743293b0dd
```
running 8 tests
test compress_65536                  ... bench:   1,382,739 ns/iter (+/- 34,707)
test compress_empty                  ... bench:         700 ns/iter (+/- 26)
test compress_hello                  ... bench:       1,000 ns/iter (+/- 35)
test decompress_after_compress_65536 ... bench:   2,366,515 ns/iter (+/- 82,848)
test decompress_after_compress_empty ... bench:         556 ns/iter (+/- 28)
test decompress_after_compress_hello ... bench:       1,017 ns/iter (+/- 27)
test decompress_big_file             ... bench:   3,896,536 ns/iter (+/- 146,913)
test decompress_huge_dict            ... bench:       1,053 ns/iter (+/- 114)
```

Probably worth pursuing in the future because of that benefit but https://github.com/chyyran/lzma-rs/commit/b46d474679df58cfe3790b522a98e3743293b0dd does it quite hackily and the RangeEncoder tests have to be reworked with a macro so I haven't bothered to clean it up.

Using https://crates.io/crates/grid to represent the literal probs matrix in `DecoderState` rather than a `Vec<Vec<u16>>` actually gave the biggest performance boost compared to master, but I'm waiting on that maintainer to merge https://github.com/becheran/grid/pull/12 for a proper fill function for use in `DecoderState::reset_state`, but that's simple enough to roll-your-own if it ends up being a blocker.

**Comment by chyyran** [comment]
`Vec2D` from #77 lets us easily experiment with different backing stores for the `literal_probs` array which is the main allocation.
I used [arrayvec](https://crates.io/crates/arrayvec) which gives us a nice API over a raw array.

Since `DecoderState` needs to be able to update lclppb at runtime, we can't just parameterize it with const generics unlike `BitTree`, so we have to account for the theoretical maximum parameters which is `sizeof(u16) * 0x300 * { 1 << (4 + 8) }` = 3145728 * 2. An array of 6 megabytes is way too large to fit on the stack and I was unable to actually decompress anything without a stack overflow.

For LZMA2 streams, the theoretical maximum parameters for the `literal_probs` array is  `sizeof(u16) * 0x300 * { 1 << 4 }` = 12288 * 2. While this isn't great, 24KB is way smaller than 6MB so I was able to actually run some benchmarks, which are not great.

These benchmarks are with an allocating `BitTree`, i.e. without const-generics.

**ArrayVec<u16, 0x300 * { 1 << 4 }>**
```
running 8 tests
test compress_65536                  ... bench:   1,323,468 ns/iter (+/- 174,348)
test compress_empty                  ... bench:         695 ns/iter (+/- 20)
test compress_hello                  ... bench:       1,035 ns/iter (+/- 90)
test decompress_after_compress_65536 ... bench:   1,336,165 ns/iter (+/- 57,379)
test decompress_after_compress_empty ... bench:       6,166 ns/iter (+/- 359)
test decompress_after_compress_hello ... bench:       6,531 ns/iter (+/- 224)
test decompress_big_file             ... bench:   3,716,763 ns/iter (+/- 121,865)
test decompress_huge_dict            ... bench:       6,572 ns/iter (+/- 315)

test result: ok. 0 passed; 0 failed; 0 ignored; 8 measured; 0 filtered out; finished in 13.64s
```

**`Box<[u16]>`**
```
running 8 tests
test compress_65536                  ... bench:   1,334,964 ns/iter (+/- 1,371,984)
test compress_empty                  ... bench:         709 ns/iter (+/- 436)
test compress_hello                  ... bench:       1,033 ns/iter (+/- 64)
test decompress_after_compress_65536 ... bench:   1,145,697 ns/iter (+/- 82,369)
test decompress_after_compress_empty ... bench:       1,890 ns/iter (+/- 92)
test decompress_after_compress_hello ... bench:       2,231 ns/iter (+/- 295)
test decompress_big_file             ... bench:   3,620,380 ns/iter (+/- 152,660)
test decompress_huge_dict            ... bench:       2,271 ns/iter (+/- 75)

test result: ok. 0 passed; 0 failed; 0 ignored; 8 measured; 0 filtered out; finished in 7.76s
```

The huge array on the stack causes a lot of cache overflows and substantially reduces performance. It seems the only benefit to using const generics here is with `BitTree`, where it does show an improvement in the benchmarks as above.
